CREATE TABLE users (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    name char(128) NOT NULL,
    email char(128)  NOT NULL,
    phone char(128)  NOT NULL,
    password char(128)  NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT users_ak_1 UNIQUE (phone),
    CONSTRAINT users_pk PRIMARY KEY  (id)
);

CREATE TABLE user_address (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    user_id int NOT NULL,
    address char(128)  NOT NULL,
    state char(128)  NOT NULL,
    city char(128)  NOT NULL,
    zipcode char(128)  NOT NULL,
    CONSTRAINT user_address_ak_1 FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT user_address_ak_2 UNIQUE (user_id),
    CONSTRAINT user_address_pk PRIMARY KEY  (id)
);


-- CREATE TABLE user_payment (
--     id int  NOT NULL IDENTITY(1, 1),
--     user_id int NOT NULL,
--     order_id int NOT NULL,
--     CONSTRAINT user_payment_ak_1 FOREIGN KEY(user_id) REFERENCES users(id)
--     CONSTRAINT user_payment_ak_2 FOREIGN KEY(order_id) REFERENCES orders(id)
-- );

