CREATE TABLE order_details (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    user_id int NOT NULL,
    total char(128) NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT order_details_pk PRIMARY KEY  (id),
    CONSTRAINT order_details_fk_2 FOREIGN KEY(user_id) REFERENCES users_management.users(id)
);


CREATE TABLE payment_details (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    order_id int NOT NULL,
    user_id int NOT NULL,
    amount char(128) NOT NULL,
    status char(128) NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT payment_details_pk PRIMARY KEY  (id),
    CONSTRAINT payment_details_fk_1 FOREIGN KEY(order_id) REFERENCES order_details(id),
    CONSTRAINT payment_details_fk_2 FOREIGN KEY(user_id) REFERENCES users_management.users(id)
);

CREATE TABLE shopping_session (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    user_id int NOT NULL,
    total char(128) NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT shopping_session_pk PRIMARY KEY  (id),
    CONSTRAINT shopping_session_fk_2 FOREIGN KEY(user_id) REFERENCES users_management.users(id)
);

CREATE TABLE cart_items (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    session_id int NOT NULL,
    product_id int NOT NULL,
    quantity int NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT cart_items_pk PRIMARY KEY  (id),
    CONSTRAINT cart_items_fk_1 FOREIGN KEY(session_id) REFERENCES shopping_session(id)
    CONSTRAINT cart_items_fk_2 FOREIGN KEY(product_id) REFERENCES products.products(id)
);



CREATE TABLE order_items (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    order_id int NOT NULL,
    product_id int NOT NULL,
    quantity int NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT order_items_pk PRIMARY KEY  (id),
    CONSTRAINT order_items_fk_1 FOREIGN KEY(order_id) REFERENCES orders.order_details(id)
    CONSTRAINT order_items_fk_2 FOREIGN KEY(product_id) REFERENCES products.products(id)
);